### ISSUE TITLE
Script not work 

### ISSUE THREAD

**Issue by bnocf** [DBanaszewski/bash-scripts#2]
1. Script not work.
2. please remove --ssh in start file.

**Comment by DBanaszewski** [comment]
@bnocf 
`Script not work.` - explain this point because I don't know what isn't work.
`please remove --ssh` - issue about this is already created - https://github.com/DBanaszewski/bash-scripts/issues/1

**Comment by bnocf** [comment]
after firing, he writes to add --ssh even if it is

**Comment by DBanaszewski** [comment]
@bnocf `after firing, he writes to add --ssh even if it is` I tested this script and it works perfectly (but we must write `-s`/`--ssh` argument).
